### ISSUE TITLE
Create NuGet package

### ISSUE THREAD

**Issue by HakanL** [mikeclayton/PiFaceSharp#3]
Would be great if you could create and publish a NuGet package for this library

**Comment by mikeclayton** [comment]
Hi,

It's something I've planned to do for a long time, but never quite found time to get round to.

However, it's now done. Check out "Kingsland.PiFaceSharp" on nuget.org!

https://www.nuget.org/packages/Kingsland.PiFaceSharp/

It also contains a merge into master of some major refactoring that was parked up on a feature branch for a while, so let me know if you have any problems using it and I'll take a look.

Cheers,

Mike

**Comment by HakanL** [comment]
Cool, thanks!
